# Generated by Django 4.1.4 on 2022-12-27 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Angkatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun', models.CharField(max_length=4)),
                ('nama_angkatan', models.CharField(default='Tidak ada', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Prodi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_prodi', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Status_Anggota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_status', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Anggota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('nim', models.CharField(max_length=20)),
                ('no_hp', models.CharField(max_length=20, null=True)),
                ('no_wa', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('tempat_lahir', models.CharField(max_length=100, null=True)),
                ('tanggal_lahir', models.DateField()),
                ('asal_daerah', models.CharField(max_length=100, null=True)),
                ('alamat_dms', models.CharField(max_length=500, null=True)),
                ('alamat_mks', models.CharField(max_length=500, null=True)),
                ('goldar', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('O', 'O'), ('AB', 'AB')], max_length=2, null=True)),
                ('minat', models.CharField(default='Tidak ada', max_length=200)),
                ('bakat', models.CharField(default='Tidak ada', max_length=200)),
                ('angkatan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.angkatan')),
                ('keterangan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.status_anggota')),
                ('prodi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.prodi')),
            ],
        ),
    ]
